version: 2
jobs:
  build:
    docker:
      - image: node:lts-alpine
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: 'prisma'
          MYSQL_DATABASE: 'tests'

    working_directory: ~/repo
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      
      - run: npm ci
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run migrations!
      - run: npm run ci:migrate
      
      # run tests!
      - run: npm run ci:test
      


  push:
    docker:
      - image: node:lts-alpine

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true      
      
      - run:
          name: Install Docker
          command: apk add docker
      
      - run:
          name: Install Docker client
          command: |
            apk add curl
            set -x
            VER="20.10.16"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Build Docker Image
          command: |
            ls -lah
            docker build -t rogerdurich/koa-framework .
      
      - run:
          name: Login & Ship Image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push rogerdurich/koa-framework:latest

workflows:
  version: 2
  build-test-and-push:
    jobs:
      - build
      - push:
          requires:
            - build