version: 2
jobs:
  test:
    docker:
      - image: node:lts-alpine
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: 'prisma'
          MYSQL_DATABASE: 'tests'

    working_directory: ~/repo
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      
      - run: npm ci
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run migrations!
      - run: npm run ci:migrate
      
      # run tests!
      - run: npm run ci:test

  build:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Docker client
          command: |
            apk add curl
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: npm run ci:docker